project:
  type: website
  resources: Assets
  

website:
  title: "Thomas Kim"
  navbar:
    background: "#E6BE8A"
    left:
      - href: index.qmd
        text: About Me
      - href: projects.qmd
        text: Project
    right:
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/thomas-kim-csom/
      - icon: github
        text: Github
        href: https://github.com/thomaskim7241
      - icon: inbox
        text: Email
        href: mailto:thomaskim7241@gmail.com
      - icon: hand-thumbs-up
        text: Handshake
        href: https://app.joinhandshake.com/profiles/cznmth
      - icon: file-earmark-person-fill
        text: Resume
        href: Assets/Resume.pdf

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.cssq
    toc: true

execute: 
  freeze: auto

